apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reemio-recommender-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: recommendation-api

  - patch: |-
      - op: replace
        path: /data/APP_ENV
        value: development
      - op: replace
        path: /data/LOG_LEVEL
        value: DEBUG
    target:
      kind: ConfigMap
      name: recommender-config
