apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recommendation-api-ingress
  namespace: reemio-recommender
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
    - hosts:
        - recommender.reemioltd.com
      secretName: recommender-tls
  rules:
    - host: recommender.reemioltd.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recommendation-api
                port:
                  number: 80
