apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reemio-recommender

resources:
  - namespace.yaml
  - configmap.yaml
  - recommendation-api/deployment.yaml
  - recommendation-api/service.yaml
  - email-worker/deployment.yaml
  - sync-worker/deployment.yaml
  - ingress.yaml
