apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reemio-recommender-staging

resources:
  - ../../base

namePrefix: staging-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: recommendation-api

  - patch: |-
      - op: replace
        path: /data/APP_ENV
        value: staging
    target:
      kind: ConfigMap
      name: recommender-config
